### ISSUE TITLE
Applications Menu ， It can't be opened after startup。

### ISSUE THREAD

**Issue by Yu-Xiao-Sheng** [elementary/applications-menu#345] opened 2020-02-22 02:02 UTC
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by IT-Tool** [comment] 2020-07-22 11:16
Duplicate of #393

**Comment by ryonakano** [comment] 2020-07-23 12:31
I'll close this as a duplicate of #393. Reopen and provide more information if it's not.

**Closed by ryonakano** 2020-07-23 12:31 UTC
