### ISSUE TITLE
Labels don't change color after switching system style

### ISSUE THREAD

**Issue by TomiOhl** [elementary/applications-menu#561] opened 2023-02-07 19:38 UTC
### What Happened?

When the system switches from light to dark mode, the labels of the applications stay dark:
![image](https://user-images.githubusercontent.com/6696659/217347099-b98f8986-9d37-40a3-994c-8b87672d98a5.png)
When I switch from dark to light mode, the labels stay white:
![image](https://user-images.githubusercontent.com/6696659/217347294-97d82170-6b92-4cf2-8e56-b8f87adfbd87.png)

The way to "fix" this is to swipe to the second page or drag an icon. The texts will render with the correct color after that.

### Steps to Reproduce

1. Open applications menu
2. Change the system style
3. Open applications menu again, and notice that the color of the texts didn't update

### Expected Behavior

The color should switch automatically

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-02-12 03:18
Duplicate of #495.

**Closed by lenemter** 2023-02-12 03:18 UTC
