### ISSUE TITLE
Application icons: Uninstall option greyed out on all icons

### ISSUE THREAD

**Issue by canopusStar** [elementary/applications-menu#544] opened 2022-07-27 05:31 UTC
![Screenshot from 2022-07-27 15 40 58](https://user-images.githubusercontent.com/54427242/181169994-d0c9be07-b508-43d3-a0d0-44d974c73093.png)
![Screenshot from 2022-07-27 15 41 16](https://user-images.githubusercontent.com/54427242/181170007-fea38839-96ba-46e9-bc76-ad4a62bcd45e.png)
Applications in the Application windows cannot be uninstalled using right-click context as uninstall option is not functional

![Screenshot from 2022-07-27 15-30-36](https://user-images.githubusercontent.com/54427242/181168605-f3f9e862-1f1d-4175-8b3c-3aac922a861c.png)

**Comment by ryonakano** [comment] 2023-10-14 07:27
Duplicate of #503

**Closed by ryonakano** 2023-10-14 07:27 UTC
