### ISSUE TITLE
HdyPaginator randomly stops working

### ISSUE THREAD

**Issue by hanaral** [elementary/applications-menu#372] opened 2020-04-19 11:31 UTC
I have not found a way to reproduce this, but sometimes the application menu's behaviour regresses to how it works without a touchpad. For example, on my laptop where the trackpad is always connected, sometimes the pages behave like they would with a scrollwheel. This same behaviour sometimes happens with my bluetooth trackpad on my desktop too.

Expected behaviour:
- Fluid 1:1 swiping between pages

Actual behaviour:
- Menu will randomly behave like it is scrolled with a mouse and no amount of restarting the menu changes this.

I suspect this has something to do with the way trackpads are picked up in Ubuntu as the same behaviour randomly occurs when I try it on pop!_OS as well

**Comment by danrabbit** [comment] 2020-04-19 15:45
The applications menu doesn’t use paginator yet so you wouldn’t ever get 1:1 tracking here. There’s a work in progress branch here: https://github.com/elementary/applications-menu/pull/360

Closing as a duplicate of https://github.com/elementary/applications-menu/issues/235

**Closed by danrabbit** 2020-04-19 15:45 UTC
