### ISSUE TITLE
Slingshot crashes once a week

### ISSUE THREAD

**Issue by giovannicaligaris** [elementary/applications-menu#52] opened 2017-10-23 13:44 UTC
I keep getting this bug with Slingshot, maybe once a week it crashes.

![screenshot from 2017-10-23 14 41 21](https://user-images.githubusercontent.com/26255347/31892300-96ffe974-b800-11e7-80ed-67198110dfd1.png)

Slingshot comes back to normal once I click on the X.

**Comment by Philip-Scott** [comment] 2017-10-23 15:03
Do you remember what you were doing when this happened? I've been trying to reproduce it for quite a while with no success

**Comment by giovannicaligaris** [comment] 2017-10-23 15:06
Yes. I was about to install a deb from Eddy and just before I clicked install and decided to open something from Slingshot and that's when it crashed.

Does that help?

**Comment by arshubham** [comment] 2017-10-23 17:54
It also happens sometimes when updating wingpanel or the wingpanel-indicators.  Killing wingpanel from terminal solves the issue.

**Comment by worldofpeace** [comment] 2017-10-30 23:02
I've had this happen numerous times during really intensive disk IO. What I see happening visually is that I click Applications and it spawn that transparent window. Sometimes I can close it and sometimes not. 
Eventually wingpanel gets restarted like @arshubham said and then it works.

**Comment by peteruithoven** [comment] 2017-12-13 00:33
I think I'm sometimes experiencing the same issue. When opening the applications menu the graphics make little sense. The categories are in their own separate window for example. 

![slingshot-2017-12-12_20 05 12 mp4](https://user-images.githubusercontent.com/523210/33915640-b6dfd396-dfa4-11e7-89b8-4974ec272649.gif)

When this happens it keeps happening until I restart the wingpanel (`killall wingpanel`). Is there any way I could debug this, get some terminal output for example? 

I'm running Elementary Loki. I'm currently using the Arc theme, but this also happened to me with the default Elementary theme. 
Please let me know if I can provide more information.

**Comment by worldofpeace** [comment] 2017-12-24 06:26
@peteruithoven Wow that's like really weird...
Hey, maybe if we scream loud enough someone might come and help :scream: :smile:

**Comment by donadigo** [comment] 2017-12-24 13:04
It happened to me a few times but it's really hard to reproduce. @peteruithoven: if the issue persists and you're able to reproduce it often, you can debug it by doing so:

1. Kill the cerbere process: `killall cerbere`
2. Kill the wingpanel process: `killall wingpanel` ( you may need to execute that twice or more times) until wingpanel disappears.

3. Then launch wingpanel from the command line: `wingpanel` and if the issue appears while running it in the terminal, copy the output of the command here, that could be really helpful. Note that you'll have to keep the terminal running since closing it will also kill the wingpanel process.

**Comment by peteruithoven** [comment] 2017-12-24 19:05
@donadigo thanks for the info but the tricky part is that a `killall wingpanel` always makes the issue dissappear... Is there any way to get debug info from the running process? Wingpanel is the process that has the issue?

**Comment by peteruithoven** [comment] 2018-01-10 10:30
I'd love to know how to debug the running wingpanel, it just happened again. 
To compare, redshift adds a systemd service, and probably related to that is that I can view it's logs by using `journalctl -u redshift`. 
Isn't there a way to get wingpanel specific logs?

**Comment by donadigo** [comment] 2018-01-15 15:47
@peteruithoven I'll see if I can submit a test branch with journal logging set as the default handler for warnings / other messages.

**Comment by peteruithoven** [comment] 2018-11-09 15:50
Since I've moved to Juno I've not seen this issue anymore. I'm closing it.

**Closed by peteruithoven** 2018-11-09 15:50 UTC
Labels: Priority: Medium, Status: Confirmed
