### ISSUE TITLE
Odd numbers displayed by the calculator plugin when typing in capitals

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/applications-menu#494] opened 2021-08-16 17:56 UTC
## What Happened
https://user-images.githubusercontent.com/13716824/129607715-80a7d3fc-f5b2-483d-a32e-61a6d4c954c7.mp4

It appears to be assigning a value to the letters with A being 10 and Z 35 etc. Once more than one character is typed it just shows a 9 for each character.

## Expected Behavior
I'm not sure on the intended usage of this. Maybe a roman numeral converter would be more useful?

## Platform Information
Odin

**Comment by cassidyjames** [comment] 2021-08-16 19:36
Thanks for reporting this! As a reminder, please search for existing issues before filing new ones. This appears to be a duplicate of #474; please add a :+1: reaction to that issue to mark it as affecting you.

**Closed by cassidyjames** 2021-08-16 19:36 UTC

**Comment by ChildishGiant** [comment] 2021-08-16 20:16
Sorry, I did search for duplicates but couldn't find this
