### ISSUE TITLE
integrate file search in application menu.

### ISSUE THREAD

**Issue by nazar2sfive** [elementary/applications-menu#320] opened 2019-11-06 15:24 UTC
i have my ntfs volume of windows as well indexed via Fsearch.

it would be of great help if this search was provided in application menu(with help of fsearch like app)

![image](https://user-images.githubusercontent.com/12841320/68311440-a424cd80-00d9-11ea-8514-61038935e5ff.png)

https://github.com/cboxdoerfer/fsearch

**Comment by peteruithoven** [comment] 2019-12-08 16:41
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/applications-menu/issues/54

**Closed by peteruithoven** 2019-12-08 16:41 UTC
