### ISSUE TITLE
weird behavior on app-menu search result when capslock is on.

### ISSUE THREAD

**Issue by wedsonlopes** [elementary/applications-menu#484] opened 2021-07-08 18:09 UTC
## What Happened
when capslock is "on" the result of any kind of search appears in numbers "9" in calculator icon

## Expected Behavior
The search results should appear normally.

## Steps to Reproduce

1.turn capslock key ON
2.Search for any application on app menu search bar

## Platform Information
Using elementary os 6 
![Screenshot from 2021-07-08 15-07-53](https://user-images.githubusercontent.com/35546352/124970552-70aceb80-dffe-11eb-84e5-c41ade8202df.png)

**Comment by cassidyjames** [comment] 2021-07-08 18:26
How strange. :joy: Thanks for reporting! I can reproduce here on elementary OS 6.

**Comment by candiedoperation** [comment] 2021-07-21 03:30
@cassidyjames, Sorry for the direct mention but, this issue was reported way back. It not only causes **99999** to appear but also causes 100% CPU utilization until logging out (or rebooting).

The below issues refer to the same issue and demonstrates the CPU Usage
- Issue https://github.com/elementary/applications-menu/issues/474
- Issue https://github.com/elementary/applications-menu/issues/475

**Comment by cassidyjames** [comment] 2021-07-21 03:40
@candiedoperation thanks for pointing that out! I'll mark this as a duplicate of #474

**Closed by cassidyjames** 2021-07-21 03:40 UTC
Labels: Status: Duplicate
