### ISSUE TITLE
Opening the menu, Wingpanel has to be force closed

### ISSUE THREAD

**Issue by lainsce** [elementary/applications-menu#190] opened 2019-04-12 20:52 UTC
Everytime I try opening the menu, I have to force close Wingpanel before using other indicators.

elementary OS 5.0 Juno

(tips on how to debug appreciated.)

**Comment by peteruithoven** [comment] 2019-04-16 21:31
Please see [elementary OS Development](https://elementary.io/docs/code/os-dev) > WingPanel and Debug logs. 

I'm not sure how, but it sounds like it's caused by an installed application, did you install something new recently?
We've for example experience issues when applications use huge application icons: https://github.com/elementary/applications-menu/issues/117

**Comment by lainsce** [comment] 2019-04-17 11:42
Apparently it fixed itself _for me_ but for others I think it's still valid, and nope, not a big icon issue.

**Comment by peteruithoven** [comment] 2019-04-20 16:36
I'm going to close this issue, since we don't have enough information and you can't reproduce it anymore. 

There also is a change @donadigo fixed it with: https://github.com/elementary/applications-menu/pull/191

**Closed by peteruithoven** 2019-04-20 16:36 UTC
Labels: Status: Incomplete
