### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by VladRossenko** [elementary/applications-menu#401] opened 2020-07-16 11:34 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**
I'd categorise this as a functionality problem, most if not all desktop environments and OS's have what's called a "global search" that enables you to search for anything within the system and file system, eOS has very limited functionality in this regard as this feature is split into 2 different areas both of which are very limited.

- Search in files via the path bar:
Most of the time it doesn't work properly, doesn't show you global results but only shows local files in the local directory, and also being very hard to navigate.

- Search in Applications-menu:
 Shows only search results for certain system settings and installed software.

Navigating the system and file system especially only by a file manager is very difficult, Some people keep quite a lot of data on their machines, being able to access that data simply by starting a quick search makes life much easier. 

**Describe the solution you'd like**
The solution I'd like to suggest is simple and consists of basically changing the "Applications-menu" to "Search-menu", adding global search for the entire file system, the icon for the "Applications-menu" already has a "magnifying glass" suggesting its a search menu but then limits the user to only searching installed software and not having any indication it can also search for certain system settings... which makes it only natural to change to "Search-menu" and simply adding all of the above functionality into a single easy to navigate interface.

**Existing work**
Each DE and OS does its slightly differently, there is "Spotlight" in macOS which is now also making its way into iOS and iPadOS, there is the "activities menu" in Gnome, and the "Search bar" in Windows.
 
**Describe alternatives you've considered**
I've tried using third party global search utilities like Albert, Catfish and Synapsis... none of them feel native to the OS, some are buggy, some are limited in their features, and some are simply hard to install for first time Linux users. 

Leaving out this kind of functionality hole especially for those who are used to global search is a big deal breaker as it makes navigating the system only in "manual mode" by directly going out on a search adventure trying to find what you need.
And of-course it makes it very hard to navigate large amounts of files, if you keep any sort of documents or photos on your machine finding what you need becomes tedious.

**Additional context**
None.

**Comment by rbreaves** [comment] 2021-04-13 23:20
I feel like this ought to be up voted. Only reason I can imagine it not getting much attention is apps like Alfred helping people search locally.

**Comment by danrabbit** [comment] 2021-04-15 23:18
Closing as a duplicate of #54

**Closed by danrabbit** 2021-04-15 23:18 UTC
