### ISSUE TITLE
[Feature Request] - "View in AppCenter" when right-clicking application icons in the menu

### ISSUE THREAD

**Issue by Schyken** [elementary/applications-menu#198] opened 2019-05-20 01:02 UTC
Was thinking it might be nice to be able to view an installed app's page in AppCenter when right clicking it in the menu.

![ViewinAppCenter](https://user-images.githubusercontent.com/20944747/57990948-3cfa5a80-7a60-11e9-8c6b-9ea09271660c.png)

_I don't really know how difficult this would be or what it might require, so I'm just throwing the idea out there._

**Comment by peteruithoven** [comment] 2019-05-20 09:18
One challenge might be that there is no direct link (please correct me if I'm wrong) between .desktop files (which Applications-menu uses) and how they where installed. Some packages will install multiple desktop files. Desktop files can be installed manually, using flatpack, snaps, AppImages, apt etc. 

As far as I know there is no easy way to determine how desktop files where installed in general?

**Comment by Schyken** [comment] 2019-05-20 12:59
You might be right. Looking at different entries now shows nothing that would really distinguish an app installed via AppCenter from any other entry. I might suggest some custom line in the .desktop file, but I fear that straying from the standardization of .desktop files may not be ideal.

**Comment by peteruithoven** [comment] 2019-05-20 13:04
Spec: https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by donadigo** [comment] 2019-05-20 13:16
App menu already knows how to deal with this, otherwise you wouldn't be able to uninstall apps from the right-click menu. All things are in place and this should be easy to implement. Look at https://github.com/elementary/applications-menu/blob/master/src/Backend/AppCenter.vala#L25 and https://github.com/elementary/applications-menu/blob/master/src/Widgets/AppEntry.vala#L301.

We just need to add a menu item that opens a URI such as `appstream://` + `appstream_comp_id`.

**Comment by cassidyjames** [comment] 2019-05-20 17:03
Please check existing issues when filing new ones. :smile: This is a duplicate of #31, opened two years ago.

**Closed by cassidyjames** 2019-05-20 17:03 UTC
