### ISSUE TITLE
wingpanel memory consumption after opening app-menu

### ISSUE THREAD

**Issue by Mynock17** [elementary/applications-menu#145] opened 2018-10-18 15:52 UTC
After booting Juno 5.0 wingpanel uses 16M (measured with smem).
After opening the app-menu 418M ...

**Comment by peteruithoven** [comment] 2018-10-18 16:36
Isn't this a duplicate of: https://github.com/elementary/applications-menu/issues/117

**Comment by Mynock17** [comment] 2018-10-18 16:44
Maybe - but this is Juno 5.0 (not beta): Something like this shouldn't happen in a final release.

**Comment by danrabbit** [comment] 2019-10-08 16:46
Closing as a duplicate of #117

**Closed by danrabbit** 2019-10-08 16:46 UTC
