### ISSUE TITLE
Application menu doesn't remember settings

### ISSUE THREAD

**Issue by Mystery47** [elementary/applications-menu#148] opened 2018-10-21 14:33 UTC
I just like to use application menus column look, but after logout, reboot or login that option have changed. It shows that you have choosed column view, but output is different and it must be checked again.

Minor bug, but i hope this got some fixing.

**Comment by peteruithoven** [comment] 2018-10-21 14:50
Thanks for the report! This is actually a duplicate of https://github.com/elementary/applications-menu/issues/146

**Closed by peteruithoven** 2018-10-21 14:50 UTC
