### ISSUE TITLE
Visual bug after update with Jetbrains Toolbox App

### ISSUE THREAD

**Issue by mitchazj** [elementary/applications-menu#57] opened 2017-11-19 01:11 UTC
Noticed an annoying visual bug after the latest round of updates to elementaryOS; the tray icon for the Jetbrains toolbox app is now 3x its normal size & reduces the amount of space available to move windows around in :)

Screenshot: https://imgur.com/a/o5Ijp

Any thoughts on what might be happening here?

**Comment by mdh34** [comment] 2017-11-25 19:33
I had the same problem but updating toolbox fixed the issue

**Comment by peteruithoven** [comment] 2018-02-09 13:35
@mitchazj are you still experiencing this issue?

**Comment by mitchazj** [comment] 2018-02-09 14:08
I haven't seen it since, no

**Comment by peteruithoven** [comment] 2018-02-09 14:51
Maybe close this issue then?

**Closed** 2018-02-09 15:50 UTC

**Comment by mitchazj** [comment] 2018-02-09 15:57
Fair call.

Still strikes me as odd that this bug could occur though - would've expected Elementary to be enforcing a size-limit on tray icons so that hostile/buggy apps don't break user experience - what if the icon had been 10x larger lol

If this (size restriction) should be the case I'd be happy to dig into the code and submit a pull request, would just need pointers on where to look haha

**Comment by donadigo** [comment] 2018-02-09 16:04
The ayatana indicator layer does this already: https://github.com/elementary/wingpanel-indicator-ayatana/blob/master/src/AyatanaIndicator.vala#L88, so the problem is not really clear here.
