### ISSUE TITLE
Shadows are cut off in the top and bottom row

### ISSUE THREAD

**Issue by fs3o5** [elementary/applications-menu#435] opened 2020-12-21 20:15 UTC
## What Happened
When you click on an icon you see that the shadows are cut off in the top and bottom row. 

## Expected Behavior
You should be able to see all shadows.

## Steps to Reproduce
Click and hold an icon.

## Platform Information
elementary OS 6

**Comment by cassidyjames** [comment] 2020-12-21 22:01
Thanks for filing! This looks like a duplicate of https://github.com/elementary/stylesheet/issues/906

**Closed by cassidyjames** 2020-12-21 22:01 UTC
