### ISSUE TITLE
[6.0] Context Menus For Some Apps Are Squashed Vertically

### ISSUE THREAD

**Issue by Schykle** [elementary/applications-menu#455] opened 2021-01-21 04:12 UTC
## What Happened
Right clicking on some applications in the Applications Menu to display their context menus will occasionally present a squashed item list. So far it does not seem to be specific to package format.

## Expected Behavior
Context menus spawn with a reasonable amount of space to display their contents.

## Steps to Reproduce

1. Right click on some of the applications in the menu

## Platform Information
6.0 daily build. 2021-01-20.

![Screenshot from 2021-01-20 21 04 00@2x](https://user-images.githubusercontent.com/58709504/105279124-21642300-5b64-11eb-8ef6-3e2270363598.png)

**Comment by ryonakano** [comment] 2021-01-21 05:21
Thank you for your report, but maybe the cause of this issue is same with #423, so I'll closing this.

**Closed by ryonakano** 2021-01-21 05:21 UTC
