### ISSUE TITLE
[Request] Make Applications Menu launch with "Windows" key only

### ISSUE THREAD

**Issue by 1LinuxGuy** [elementary/applications-menu#33] opened 2017-07-27 17:40 UTC
I think this is the "expected" way by users to launch the Applications Menu.

Right now, this can be achieve by performing this in the Terminal. 

gsettings set org.gnome.mutter overlay-key "'Super_L'"

gsettings set org.pantheon.desktop.gala.behavior overlay-action "'wingpanel --toggle-indicator=app-launcher'"

Your call.  :-)

**Comment by cassidyjames** [comment] 2017-08-08 15:49
Since the Super key is a modifier, setting the launcher to use it means breaking all keyboard shortcuts that use Super. Which is all shell- and window-related shortcuts.

A workaround for this that has been discussed and dismissed is that we could _always_ listen for and intercept the super key, and then launch the applications menu when it's pressed and released without intermittent keys (an approach Unity and GNOME Shell both take, I believe). The problem there is that it's a lot more code prone to break a lot more things.

**Comment by donadigo** [comment] 2017-09-14 21:16
I'm reopening this. The "workaround" although, it's not really a workaround works for me and I can open Slingshot as well as perform all the gala's Super+A, Super+W, Super+S etc. The Slingshot is opened only when you release Super and not press any other keys.

**Comment by 1Claude** [comment] 2017-09-16 04:48
@donadigo 

All work for me too. It doesn't break anything I can see. Maybe I'm missing something. But I'm not a dev. So, like I said : your call.

**Comment by uncertainquark** [comment] 2017-11-01 13:51
It is working for me too. The application menu opens only after I release the Super key. All the other Super + key shortcuts work as expected too. There doesn't seem to be any breakage. 

IMO, it is important to have only 'Super' to open applications  menu as it is the expected behavior for the Start Menu in Windows the users of which elementary os is targeting. It is also expected for people transitioning from Unity or GNOME, both of which are plenty. 

It also makes for ease of use.

**Comment by wolfcry0** [comment] 2017-11-01 15:45
In windows the super key opens the start menu and also works as a modifier at the same time, why not replicate this so it has the expected behavior?

**Comment by donadigo** [comment] 2017-11-01 18:08
Closing this and reopening under the right project: https://github.com/elementary/default-settings/issues/3.

**Closed by donadigo** 2017-11-01 18:08 UTC

**Comment by cassidyjames** [comment] 2017-11-02 15:28
@wolfcry0 the argument was never that it was impossible, but that it was technically hacky to implement. It sounds like something may have changed in GNOME Settings Daemon with regard to how it listens for keyboard shortcuts, which could let us make this change. We're considering it for elementary OS Juno, but you're welcome to try out the solution from @1LinuxGuy on Loki in the meantime.
