### ISSUE TITLE
Wingpanel crashes on guest account

### ISSUE THREAD

**Issue by midwesterntechnology** [elementary/applications-menu#393] opened 2020-05-25 22:55 UTC
See attached error. Wingpanel crashes when I click on applications. Fresh guest account, haven't done anything else besides try to pull up the applications menu on wingpanel. The indicators all seem to work fine.

![Screenshot from 2020-05-25 18-49-56](https://user-images.githubusercontent.com/946543/82846936-401cf780-9eb9-11ea-81fb-b99c9446f598.png)

**Comment by 4jNsY6fCVqZv** [comment] 2020-06-21 12:51
Exciting. I also experience this in my normal user account. And it has also only been appearing recently. However, I cannot yet say exactly how the issue can be reproduced.

And I wonder if there is a connection to https://github.com/elementary/applications-menu/issues/386.

@davidmhewitt If you can take a look at it, that would be wonderful! If I can support you with information, please let me know what exactly helps you.

**Comment by IT-Tool** [comment] 2020-07-22 11:03
It happens every time when i try to **enter like a guest**. Sometimes it also **happened under the main user**.
I also noticed this bug before installation **when I boot from live CD** (without installing OS).
So it's a common bug.
![Screenshot from 2020-07-22+](https://user-images.githubusercontent.com/53435741/88168994-ed935980-cc23-11ea-886f-e0233637cf97.png)

**Comment by Borderliner** [comment] 2020-08-09 19:33
I suspect that the Wingpanel fails once, doesn't recover/kill itself properly so the access to D-Bus is not terminated, and then Pantheon tries to open Wingpanel again but fails due to the D-Bus connection already present. Any thoughts?

**Comment by mcclurgm** [comment] 2020-08-14 19:20
In my experience, it always gets reopened once, and then never again. I'm not sure what the distinction is here, since I imagine it's being run by Cerebre which should keep it running indefinitely.

One thing that seems to be common is permission errors with snaps. I see that on my account, and that's what @IT-Tool is seeing too. That may be a good place to start to track this down.

Here's a log of what I see when I open wingpanel in terminal and click on the applications menu:
```
Gtk-Message: 15:17:26.312: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 15:17:26.312: Failed to load module "appmenu-gtk-module"

** (wingpanel:18420): WARNING **: 15:17:30.466: AsyncImage.vala:384: Error opening file /snap/clion/123/bin/clion.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.467: AsyncImage.vala:384: Error opening file /snap/libreoffice/183/usr/share/icons/gnome/256x256/apps/libreoffice6.4-math.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.467: AsyncImage.vala:384: Error opening file /snap/libreoffice/183/usr/share/icons/gnome/256x256/apps/libreoffice6.4-impress.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.467: AsyncImage.vala:384: Error opening file /snap/libreoffice/183/usr/share/icons/gnome/256x256/apps/libreoffice6.4-draw.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.467: AsyncImage.vala:384: Error opening file /snap/libreoffice/183/usr/share/icons/gnome/256x256/apps/libreoffice6.4-calc.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.467: AsyncImage.vala:384: Error opening file /snap/libreoffice/183/usr/share/icons/gnome/256x256/apps/libreoffice6.4-base.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.467: AsyncImage.vala:384: Error opening file /snap/libreoffice/183/usr/share/icons/gnome/256x256/apps/libreoffice6.4-startcenter.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.469: AsyncImage.vala:384: Error opening file /snap/libreoffice/183/usr/share/icons/gnome/256x256/apps/libreoffice6.4-writer.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.469: AsyncImage.vala:384: Error opening file /snap/spotify/41/usr/share/spotify/icons/spotify-linux-128.png: Permission denied

** (wingpanel:18420): WARNING **: 15:17:30.470: AsyncImage.vala:384: Error opening file /snap/pycharm-educational/27/bin/pycharm.png: Permission denied
** Message: 15:17:30.473: DBusService.vala:64: Service registration suceeded

** (wingpanel:18420): WARNING **: 15:17:30.658: desktop-file-service.vala:117: GNOME-Flashback is not understood

** (wingpanel:18420): WARNING **: 15:17:30.659: desktop-file-service.vala:117: GNOME-Flashback is not understood

** (wingpanel:18420): WARNING **: 15:17:30.667: desktop-file-service.vala:117: ubuntu is not understood

** (wingpanel:18420): ERROR **: 15:17:30.851: worker-link.vala:83: Failed to create D-Bus server: Error binding to address: Permission denied
Trace/breakpoint trap
```

This is happening to me on Hera FWIW. So it's not new to 6.0.

**Comment by 4jNsY6fCVqZv** [comment] 2020-08-28 10:24
> In my experience, it always gets reopened once, and then never again.
This is happening to me on Hera FWIW. So it's not new to 6.0.

Can confirm both from my perspective.

**Comment by mcclurgm** [comment] 2020-09-03 23:40
Only guest for me, at least that I know for sure. I've seen a couple odd crashes in my own account that happen when I open the app menu, but never been able to track them down, so I can't tell if they're related.

**Comment by davidmhewitt** [comment] 2020-10-14 08:35
This appears to be a regression of #354 

In a guest session, AppArmor blocks the new switchboard process from listening on a socket. We probably need to ship an AppArmor profile addon (unsure of correct terminology) to allow the specific process to listen on `/tmp/applications-menu*` or whatever the path is to get this feature to work correctly.

**Comment by maloja** [comment] 2020-11-10 22:52
I can confirm. AppArmor plays a role and blocks the applications-menu from binding a socket. The kern.log file shows the denied requests. To allow binding a socket in guest sessions, i added the following lines in the profile `/etc/apparmor.d/lightdm-guest-session` and the applications-menu works fine.
```
# applications-menu
  unix (bind, listen) type=stream addr="@/tmp/applications-menu*",
```

With that some other warnings about blocked file came up. To get rid of these too, the profile needs some extra lines.

```
  @{PROC}/1/sched r,
  @{PROC}/1/cgroup r,
  @{PROC}/sys/kernel/* r,
  @{PROC}/*/fd/ r,
  /run/systemd/journal/dev-log w,
  /run/systemd/journal/stdout w,
  /run/systemd/journal/socket w,
```

**Comment by Borderliner** [comment] 2020-11-22 14:57
@maloja  Hey, thanks! Hope we see this fixed in the upcoming eOS 6.

**Closed** 2021-06-10 19:19 UTC
Labels: Priority: Critical, Status: Confirmed
