### ISSUE TITLE
The padding between the icons keeps changing randomly

### ISSUE THREAD

**Issue by uncertainquark** [elementary/applications-menu#23] opened 2017-06-08 04:55 UTC
So the default spacing between the icons which looks like this:

![screenshot from 2017-06-07 12-34-43](https://user-images.githubusercontent.com/22585732/26912800-7a80231e-4c34-11e7-8267-f525c5c3c3a5.png)

sometimes abruptly changes to this:

![screenshot from 2017-06-07 11-16-44](https://user-images.githubusercontent.com/22585732/26912815-873cf91a-4c34-11e7-93e0-a7ddf1df697f.png)

**Comment by Djaler** [comment] 2017-06-08 06:31
I can confirm this

**Comment by DanyGee** [comment] 2017-07-11 21:02
I also confirm this
![zrzut ekranu z 2017-07-09 10-34-23](https://user-images.githubusercontent.com/26818551/28090537-f0b1392a-668c-11e7-8453-979e120dab39.png)
![zrzut ekranu z 2017-07-11 22-57-09](https://user-images.githubusercontent.com/26818551/28090541-f53704ca-668c-11e7-9200-668582906983.png)

**Comment by Astro-City** [comment] 2017-12-05 23:11
This also happens to me, but i haven't found out yet what triggers it.

**Comment by DanyGee** [comment] 2018-12-07 18:10
Here is a bunch of useful info:
- single display config
- happened on two machines, one connected to 55" TV @ 3840x2160, second connected to 21" monitor @ 1920x1080
- it was happening on LOKI
- **didn't** experience it yet on JUNO on my both machines

**Comment by Djaler** [comment] 2018-12-07 19:14
I have one 15.6" 1920x1080 monitor. Didn't remeber this on Juno too

**Comment by uncertainquark** [comment] 2018-12-08 06:53
> @uncertainquark @Djaler @DanyGee @Blast-City do you all use multiple displays? Are you on loDPI or HiDPI? I think we'll need more information to track this down and reliably reproduce it in order to even begin attempting to fix it.

@cassidyjames Nope, have a single monitor and a display with a 1366 x 768 pixels. Dell Inspiron 3467 if that helps.

**Comment by Blast-City** [comment] 2018-12-13 04:48
Computer #1 Desktop 1920x1080, single monitor running Loki.
Computer #2 Laptop 1280x800 single monitor running Loki.

I haven't test it on Juno.

**Comment by arshubham** [comment] 2019-09-19 18:21
Haven't noticed this in a long while. Anyone still having issues with juno?

**Comment by DanyGee** [comment] 2019-09-19 19:44
No, didn't happen a single time in JUNO :ok_hand:

**Comment by Blast-City** [comment] 2019-09-19 21:46
No. I don't get this issue on Juno.

**Comment by arshubham** [comment] 2019-09-20 04:22
Closing this due to multiple confirmations.

**Closed by arshubham** 2019-09-20 04:22 UTC
Labels: Status: Incomplete
